nelmio_api_doc:
    documentation:
        info:
            title: API for library by Kazakov Pavel
            description: This is library API
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/v1 # Accepts routes under /api except /api/doc
