version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: postgres
      # You should definitely change the password in production
      POSTGRES_PASSWORD: 12
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

